### ISSUE TITLE
how to extract classes using @apply directive 

### ISSUE THREAD

**Issue by rajesh-vishwa** [oscar-marion/tailwind-cra-tutorial#1]
Please let me know how to use @apply directive

**Comment by oscar-marion** [comment]
@rajesh-vishwa Exactly as explained in the official documentation: [Extracting components](https://tailwindcss.com/docs/extracting-components).

```css
// index.css
.custom-button {
    @apply text-accent bg-secondary rounded mt-2 px-2
}
```

And using it in your component:
```jsx
<a 
    className="custom-button"
    href="#"`
    target="_blank"
    onClick={handleSwitchTheme}
    rel="noopener noreferrer"
>
    Switch theme
</a>
```

You will need to restart the postcss build though.
